# Copyright (c) 2026 CEA LIST / Kunal Suri. All rights reserved.
# Licensed under the Eclipse Public License v2.0 (EPL-2.0)
#Requires -Version 5.1
<#
.SYNOPSIS
    Verifies backend (Java / GraphQL / Grammar) claims in the ai/ knowledge-layer catalogs.

.DESCRIPTION
    Reads FEATURE_CATALOG.md and FEATURE_CATALOG_BACKEND.md (from ai/analysis/)
    plus MODULE_MAP.md, ARCHITECTURE.md, and FEATURE_MAP.md (from ai/guide/).
    Extracts every backtick-quoted .java / .graphqls / .g4 claim, cross-checks each
    against the actual backend/ source tree, and produces:
      - ai/analysis/audit-reports/VERIFICATION_MANIFEST_BACKEND.json  (structured claims)
      - ai/analysis/audit-reports/BACKEND_VERIFICATION_REPORT.md      (human-readable results)

    Phase 1 — Generate: parse Markdown → write / merge manifest.
    Phase 2 — Verify:   scan backend/ once, check every claim, write report.
    Both phases run by default.

.PARAMETER GenerateOnly
    Parse Markdown and update the manifest only; skip codebase scan.

.PARAMETER VerifyOnly
    Verify the existing manifest against the codebase; skip Markdown re-parsing.

.PARAMETER RepoRoot
    Repository root. Defaults to the parent of the scripts-spp/ directory.

.EXAMPLE
    .\scripts-spp\verify-ai-docs-backend.ps1
    .\scripts-spp\verify-ai-docs-backend.ps1 -GenerateOnly
    .\scripts-spp\verify-ai-docs-backend.ps1 -VerifyOnly
#>
[CmdletBinding()]
param(
    [switch]$GenerateOnly,
    [switch]$VerifyOnly,
    [string]$RepoRoot = (Split-Path $PSScriptRoot -Parent)
)

$ErrorActionPreference = "Stop"

$guideDir     = Join-Path $RepoRoot "ai\guide"
$analysisDir  = Join-Path $RepoRoot "ai\analysis"
$reportsDir   = Join-Path $analysisDir "audit-reports"
$manifestFile  = Join-Path $reportsDir "VERIFICATION_MANIFEST_BACKEND.json"
$reportFile    = Join-Path $reportsDir "BACKEND_VERIFICATION_REPORT.md"

if (-not (Test-Path $reportsDir)) { New-Item -ItemType Directory -Path $reportsDir | Out-Null }

# Catalog files that contain backend claims — current ai/ layout (ai-fication-kit 0.1.0):
# FEATURE_CATALOG*.md live in ai/analysis/; nav docs live in ai/guide/.
$CatalogFilePaths = @(
    (Join-Path $analysisDir "FEATURE_CATALOG.md"),
    (Join-Path $analysisDir "FEATURE_CATALOG_BACKEND.md"),
    (Join-Path $guideDir    "MODULE_MAP.md"),
    (Join-Path $guideDir    "ARCHITECTURE.md"),
    (Join-Path $guideDir    "FEATURE_MAP.md")
)

# EMF-generated implementation files — auto-generated by Eclipse Modeling Framework,
# not meaningful to document. Excluded from the coverage gap count.
$EmfGeneratedPattern = "Impl\.java$|ItemProvider\.java$|AdapterFactory\.java$|Switch\.java$|package-info\.java$|Test\.java$|IT\.java$"

# ─── Helpers ──────────────────────────────────────────────────────────────────

function Get-GitCommit {
    try { return (git -C $RepoRoot rev-parse --short HEAD 2>$null).Trim() }
    catch { return "unknown" }
}

function Get-Confidence {
    param([string]$Line)
    if ($Line -match '`\[v\]`|\[verified\]') { return "verified" }
    if ($Line -match '\[inferred\]')          { return "inferred"  }
    return "unknown"
}

# ─── Phase 1: Extract backend claims from Markdown ────────────────────────────

function Extract-BackendClaims {
    param([string]$Content, [string]$SourceFile)

    $claims    = [System.Collections.Generic.List[PSCustomObject]]::new()
    $localSeen = [System.Collections.Generic.HashSet[string]]::new()

    foreach ($line in ($Content -split "`n")) {

        # Java class names — bare: `ClassName.java`  OR path: `path/to/ClassName.java`
        foreach ($m in [regex]::Matches($line, '`(?:[A-Za-z0-9_.-]+/)*([A-Z][A-Za-z0-9]+)\.java`')) {
            $id = "java_$($m.Groups[1].Value)"
            if ($localSeen.Add($id)) {
                $null = $claims.Add([PSCustomObject]@{
                    id         = $id
                    type       = "java"
                    name       = $m.Groups[1].Value
                    fileName   = "$($m.Groups[1].Value).java"
                    sourceFile = $SourceFile
                    confidence = Get-Confidence $line
                    status     = "pending"
                    foundAt    = $null
                    note       = $null
                })
            }
        }

        # GraphQL schema files — bare: `name.graphqls`  OR path: `path/to/name.graphqls`
        foreach ($m in [regex]::Matches($line, '`(?:[A-Za-z0-9_.-]+/)*([A-Za-z][A-Za-z0-9_.-]+\.graphqls)`')) {
            $id = "graphql_$($m.Groups[1].Value -replace '[^A-Za-z0-9]', '_')"
            if ($localSeen.Add($id)) {
                $null = $claims.Add([PSCustomObject]@{
                    id         = $id
                    type       = "graphql"
                    name       = $m.Groups[1].Value
                    fileName   = $m.Groups[1].Value
                    sourceFile = $SourceFile
                    confidence = Get-Confidence $line
                    status     = "pending"
                    foundAt    = $null
                    note       = $null
                })
            }
        }

        # ANTLR grammar files — bare: `Name.g4`  OR path: `path/to/Name.g4`
        foreach ($m in [regex]::Matches($line, '`(?:[A-Za-z0-9_.-]+/)*([A-Za-z][A-Za-z0-9_.-]+\.g4)`')) {
            $id = "g4_$($m.Groups[1].Value -replace '[^A-Za-z0-9]', '_')"
            if ($localSeen.Add($id)) {
                $null = $claims.Add([PSCustomObject]@{
                    id         = $id
                    type       = "grammar"
                    name       = $m.Groups[1].Value
                    fileName   = $m.Groups[1].Value
                    sourceFile = $SourceFile
                    confidence = Get-Confidence $line
                    status     = "pending"
                    foundAt    = $null
                    note       = $null
                })
            }
        }
    }

    return $claims
}

# ─── Phase 2: Single-pass codebase indexing ───────────────────────────────────

function Build-FileIndex {
    param([string]$SearchDir, [string[]]$Extensions, [string]$Label)

    Write-Host "    Indexing $Label ..." -ForegroundColor DarkGray
    $index = @{}
    if (-not (Test-Path $SearchDir)) {
        Write-Host "    WARNING: directory not found: $SearchDir" -ForegroundColor DarkYellow
        return $index
    }

    Get-ChildItem -Path $SearchDir -Recurse -File -ErrorAction SilentlyContinue |
        Where-Object { $Extensions -contains $_.Extension.TrimStart('.') } |
        ForEach-Object {
            $rel = $_.FullName.Replace($RepoRoot, "").TrimStart('\/')
            if (-not $index.ContainsKey($_.Name)) {
                $index[$_.Name] = $rel
            } else {
                $prior = $index[$_.Name]
                if ($prior -is [string]) {
                    $list = [System.Collections.Generic.List[string]]::new()
                    $list.Add($prior); $list.Add($rel); $index[$_.Name] = $list
                } else { $index[$_.Name].Add($rel) }
            }
        }
    return $index
}

# ─── Phase 3: Verify each claim ───────────────────────────────────────────────

function Resolve-Claim {
    param([PSCustomObject]$Claim, [hashtable]$JavaIdx, [hashtable]$GqlIdx, [hashtable]$GrammarIdx)

    # Pattern-documentation entries (Xxx placeholder) document a naming convention,
    # not a real file. Treat as informational, not as an error.
    if ($Claim.fileName -match 'Xxx') {
        $Claim.status = "pattern_template"
        $Claim.note   = "Template placeholder — 'Xxx' replaced by actual node type name in real files"
        return $Claim
    }

    $idx = switch ($Claim.type) {
        "java"    { $JavaIdx    }
        "graphql" { $GqlIdx     }
        "grammar" { $GrammarIdx }
        default   { $null       }
    }

    if ($null -eq $idx -or -not $idx.ContainsKey($Claim.fileName)) {
        $Claim.status = "not_found"
        return $Claim
    }

    $entry = $idx[$Claim.fileName]
    if ($entry -is [string]) {
        $Claim.status  = "confirmed"
        $Claim.foundAt = $entry
    } else {
        $Claim.status  = "confirmed_multiple"
        $Claim.foundAt = ($entry -join " | ")
        $Claim.note    = "Filename is not unique — $($entry.Count) matches found"
    }
    return $Claim
}

# ─── Phase 4: Coverage gap analysis ──────────────────────────────────────────

function Get-BackendCoverageStats {
    param([hashtable]$JavaIdx, [array]$Claims)

    # Business-logic Java: exclude EMF-generated boilerplate
    $businessJava = $JavaIdx.Keys | Where-Object { $_ -notmatch $EmfGeneratedPattern } | Sort-Object
    $docJava      = @($Claims | Where-Object { $_.type -eq "java" -and $_.status -like "confirmed*" } |
                      Select-Object -ExpandProperty fileName)

    return [PSCustomObject]@{
        javaTotal      = $businessJava.Count
        javaDocumented = ($businessJava | Where-Object { $docJava -contains $_ }).Count
        javaGaps       = @($businessJava | Where-Object { $docJava -notcontains $_ })
    }
}

# ─── Phase 5: Write backend report ────────────────────────────────────────────

function Write-BackendReport {
    param([array]$Claims, [PSCustomObject]$Cov, [string]$Commit)

    $now       = Get-Date -Format "yyyy-MM-ddTHH:mm:ss"
    $confirmed = @($Claims | Where-Object { $_.status -like "confirmed*" })
    $notFound  = @($Claims | Where-Object { $_.status -eq "not_found" })
    $patterns  = @($Claims | Where-Object { $_.status -eq "pattern_template" })
    $total     = $Claims.Count

    $Pct = { param($n, $d) if ($d -gt 0) { "$([math]::Round($n / $d * 100))%" } else { "n/a" } }
    $jPct = if ($Cov.javaTotal -gt 0) { [math]::Round($Cov.javaDocumented / $Cov.javaTotal * 100) } else { 0 }

    $sb = [System.Text.StringBuilder]::new()
    $null = $sb.AppendLine("<!-- Copyright (c) 2026 CEA LIST / Kunal Suri. All rights reserved. -->")
    $null = $sb.AppendLine("# Backend Verification Report — SysON++")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("> **Generated:** $now")
    $null = $sb.AppendLine("> **Repo commit:** ``$Commit``")
    $null = $sb.AppendLine("> **Manifest:** ``ai/analysis/audit-reports/VERIFICATION_MANIFEST_BACKEND.json``")
    $null = $sb.AppendLine("> **Scope:** Java classes · GraphQL schemas · ANTLR grammars")
    $null = $sb.AppendLine("> **Total claims checked:** $total")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("---")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("## Summary")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("| Status | Count | % of claims |")
    $null = $sb.AppendLine("|---|---|---|")
    $null = $sb.AppendLine("| ✅ Confirmed (file found in backend/) | $($confirmed.Count) | $(&$Pct $confirmed.Count $total) |")
    $null = $sb.AppendLine("| ❌ Not found — fix or remove from catalog | $($notFound.Count) | $(&$Pct $notFound.Count $total) |")
    $null = $sb.AppendLine("| 📐 Pattern template (intentional Xxx placeholder) | $($patterns.Count) | $(&$Pct $patterns.Count $total) |")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("### Backend catalog coverage")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("> Percentage of actual ``backend/`` source files documented in the ai/ knowledge layer.")
    $null = $sb.AppendLine("> EMF-generated ``*Impl``, ``*ItemProvider``, ``*Switch``, ``*AdapterFactory`` files are excluded.")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("| Type | In codebase | In catalog | Coverage |")
    $null = $sb.AppendLine("|---|---|---|---|")
    $null = $sb.AppendLine("| Java business-logic classes | $($Cov.javaTotal) | $($Cov.javaDocumented) | $jPct% |")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("---")

    # Not-found
    if ($notFound.Count -gt 0) {
        $null = $sb.AppendLine("")
        $null = $sb.AppendLine("## ❌ Not Found — Fix These ($($notFound.Count))")
        $null = $sb.AppendLine("")
        $null = $sb.AppendLine("> These names appear in the ai/ catalogs but **no matching file exists** in ``backend/``.")
        $null = $sb.AppendLine("> They are likely hallucinated, renamed, or deleted. Open the source catalog and fix or delete each row.")
        $null = $sb.AppendLine("")
        $null = $sb.AppendLine("| Claimed File | Type | Confidence | Source Catalog |")
        $null = $sb.AppendLine("|---|---|---|---|")
        foreach ($c in ($notFound | Sort-Object sourceFile, fileName)) {
            $null = $sb.AppendLine("| ``$($c.fileName)`` | $($c.type) | $($c.confidence) | [$($c.sourceFile)](../$(($c.sourceFile))) |")
        }
        $null = $sb.AppendLine("")
        $null = $sb.AppendLine("---")
    }

    # Pattern templates
    if ($patterns.Count -gt 0) {
        $null = $sb.AppendLine("")
        $null = $sb.AppendLine("## 📐 Pattern Templates ($($patterns.Count) entries)")
        $null = $sb.AppendLine("")
        $null = $sb.AppendLine("> These use ``Xxx`` as a placeholder documenting a naming convention, not a real file.")
        $null = $sb.AppendLine("> Replace ``Xxx`` with a node type name (``Package``, ``Note``, ``ViewFrame``, ``ImportedPackage``) to get actual files.")
        $null = $sb.AppendLine("")
        $null = $sb.AppendLine("| Template | Source |")
        $null = $sb.AppendLine("|---|---|")
        foreach ($c in ($patterns | Sort-Object fileName)) {
            $null = $sb.AppendLine("| ``$($c.fileName)`` | $($c.sourceFile) |")
        }
        $null = $sb.AppendLine("")
        $null = $sb.AppendLine("---")
    }

    # Coverage gaps
    if ($Cov.javaGaps.Count -gt 0) {
        $showN = [math]::Min($Cov.javaGaps.Count, 80)
        $note  = if ($Cov.javaGaps.Count -gt 80) { "Top $showN of $($Cov.javaGaps.Count) shown." } else { "All $($Cov.javaGaps.Count) shown." }
        $null = $sb.AppendLine("")
        $null = $sb.AppendLine("## Coverage Gaps — Java Classes Not in Catalog ($($Cov.javaGaps.Count))")
        $null = $sb.AppendLine("")
        $null = $sb.AppendLine("> Business-logic ``.java`` files in ``backend/`` that are **not mentioned** in any ai/ knowledge file. $note")
        $null = $sb.AppendLine("")
        $Cov.javaGaps | Select-Object -First 80 | ForEach-Object { $null = $sb.AppendLine("- ``$_``") }
        $null = $sb.AppendLine("")
        $null = $sb.AppendLine("---")
    }

    # Confirmed
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("## ✅ Confirmed Claims ($($confirmed.Count))")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("<details>")
    $null = $sb.AppendLine("<summary>Expand to see all confirmed claims with verified file locations</summary>")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("| File | Type | Confidence | Source | Found At |")
    $null = $sb.AppendLine("|---|---|---|---|---|")
    foreach ($c in ($confirmed | Sort-Object type, fileName)) {
        $at   = if ($c.foundAt) { "``$($c.foundAt)``" } else { "—" }
        $note = if ($c.note)    { " ⚠️ $($c.note)"    } else { "" }
        $null = $sb.AppendLine("| ``$($c.fileName)`` | $($c.type) | $($c.confidence) | $($c.sourceFile) | $at$note |")
    }
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("</details>")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("---")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("## Human Audit Checklist (Backend)")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("Automated checks verify **file existence only**. Descriptions require human eyes:")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("- [ ] **Fix every ❌ Not Found** — open the source catalog, correct the filename or delete the row.")
    $null = $sb.AppendLine("- [ ] **Audit ``[inferred]`` descriptions** — open each confirmed-but-inferred Java class and verify")
    $null = $sb.AppendLine("       the stated responsibility is accurate. Mark ``[verified]`` in the catalog when done.")
    $null = $sb.AppendLine("- [ ] **Audit Status column** — every ``?`` in MODULE_MAP.md needs a human decision:")
    $null = $sb.AppendLine("       ``frozen`` / ``ours`` / ``stable``. Use ``git log -- <path>`` to check authorship.")
    $null = $sb.AppendLine("- [ ] **Review Coverage Gaps** — decide if any undocumented class belongs in the catalog.")
    $null = $sb.AppendLine("- [ ] **Re-run** after fixes: ``.\scripts-spp\verify-ai-docs-backend.ps1``")

    Set-Content -Path $reportFile -Value $sb.ToString() -Encoding UTF8
}

# ═══ Main ═════════════════════════════════════════════════════════════════════

Write-Host ""
Write-Host "╔══════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  Backend Verification Tool — SysON++        ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host "  Repo: $RepoRoot"
Write-Host ""

$runGenerate = -not $VerifyOnly.IsPresent
$runVerify   = -not $GenerateOnly.IsPresent

$allClaims = [System.Collections.Generic.List[PSCustomObject]]::new()

# ── Phase 1: Extract backend claims ─────────────────────────────────────────

if ($runGenerate) {
    Write-Host "[Phase 1/4] Extracting backend claims from ai/ knowledge-layer Markdown..." -ForegroundColor Yellow

    $globalSeen = [System.Collections.Generic.HashSet[string]]::new()

    foreach ($fp in $CatalogFilePaths) {
        $fn = Split-Path $fp -Leaf
        if (-not (Test-Path $fp)) {
            Write-Host "    SKIP (not found): $fn" -ForegroundColor DarkGray
            continue
        }
        $extracted = Extract-BackendClaims -Content (Get-Content $fp -Raw) -SourceFile $fn
        $added = 0
        foreach ($c in $extracted) {
            if ($globalSeen.Add($c.id)) { $allClaims.Add($c); $added++ }
        }
        Write-Host "    $fn  →  $added claims"
    }

    Write-Host "  Total unique backend claims: $($allClaims.Count)"

    # Merge with existing manifest — preserve prior verification status
    if (Test-Path $manifestFile) {
        try {
            $prior = Get-Content $manifestFile -Raw | ConvertFrom-Json
            $priorMap = @{}
            foreach ($e in $prior.claims) { $priorMap[$e.id] = $e }
            $preserved = 0
            foreach ($c in $allClaims) {
                if ($priorMap.ContainsKey($c.id) -and $priorMap[$c.id].status -ne "pending") {
                    $c.status  = $priorMap[$c.id].status
                    $c.foundAt = $priorMap[$c.id].foundAt
                    $c.note    = $priorMap[$c.id].note
                    $preserved++
                }
            }
            Write-Host "  Merged with prior manifest — $preserved prior results preserved."
        } catch {
            Write-Host "  Warning: existing manifest could not be parsed; starting fresh." -ForegroundColor DarkYellow
        }
    }

    $manifest = [ordered]@{
        _comment    = "Auto-generated by scripts-spp/verify-ai-docs-backend.ps1 — safe to edit manually"
        generated   = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss")
        repoCommit  = (Get-GitCommit)
        scope       = "backend — Java, GraphQL, Grammar"
        totalClaims = $allClaims.Count
        claims      = @($allClaims)
    }
    $manifest | ConvertTo-Json -Depth 10 | Set-Content -Path $manifestFile -Encoding UTF8
    Write-Host ""
    Write-Host "  ✅ Manifest written: $manifestFile  ($($allClaims.Count) claims)" -ForegroundColor Green
}

# ── Phase 2: Load manifest for VerifyOnly ────────────────────────────────────

if ($runVerify -and $allClaims.Count -eq 0) {
    if (-not (Test-Path $manifestFile)) {
        Write-Error "Manifest not found at '$manifestFile'. Run without -VerifyOnly first."
    }
    $existing = Get-Content $manifestFile -Raw | ConvertFrom-Json
    foreach ($e in $existing.claims) { $allClaims.Add($e) }
    Write-Host "[Loaded backend manifest: $($allClaims.Count) claims]"
}

# ── Phase 3: Codebase scan & verify ─────────────────────────────────────────

if ($runVerify) {
    Write-Host ""
    Write-Host "[Phase 2/4] Indexing backend/ source tree..." -ForegroundColor Yellow

    $javaIdx    = Build-FileIndex -SearchDir (Join-Path $RepoRoot "backend") -Extensions @("java")    -Label "backend/ *.java"
    $gqlIdx     = Build-FileIndex -SearchDir $RepoRoot                        -Extensions @("graphqls") -Label "*.graphqls"
    $grammarIdx = Build-FileIndex -SearchDir $RepoRoot                        -Extensions @("g4")       -Label "*.g4"

    Write-Host ""
    Write-Host "    Java files indexed   : $($javaIdx.Count)"
    Write-Host "    GraphQL schemas      : $($gqlIdx.Count)"
    Write-Host "    Grammar files        : $($grammarIdx.Count)"

    Write-Host ""
    Write-Host "[Phase 3/4] Verifying $($allClaims.Count) backend claims..." -ForegroundColor Yellow

    $resolved = [System.Collections.Generic.List[PSCustomObject]]::new()
    foreach ($c in $allClaims) {
        $resolved.Add((Resolve-Claim -Claim $c -JavaIdx $javaIdx -GqlIdx $gqlIdx -GrammarIdx $grammarIdx))
    }

    Write-Host ""
    Write-Host "[Phase 4/4] Coverage analysis & report..." -ForegroundColor Yellow
    $cov = Get-BackendCoverageStats -JavaIdx $javaIdx -Claims @($resolved)
    Write-Host "    Java coverage : $($cov.javaDocumented) / $($cov.javaTotal) business-logic classes"

    Write-BackendReport -Claims @($resolved) -Cov $cov -Commit (Get-GitCommit)

    # Update manifest with resolved status
    $manifest = [ordered]@{
        _comment    = "Auto-generated by scripts-spp/verify-ai-docs-backend.ps1 — safe to edit manually"
        generated   = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss")
        repoCommit  = (Get-GitCommit)
        scope       = "backend — Java, GraphQL, Grammar"
        totalClaims = $resolved.Count
        claims      = @($resolved)
    }
    $manifest | ConvertTo-Json -Depth 10 | Set-Content -Path $manifestFile -Encoding UTF8

    # Console summary
    $confirmed = @($resolved | Where-Object { $_.status -like "confirmed*" })
    $notFound  = @($resolved | Where-Object { $_.status -eq "not_found" })
    $patterns  = @($resolved | Where-Object { $_.status -eq "pattern_template" })
    $jPct      = if ($cov.javaTotal -gt 0) { [math]::Round($cov.javaDocumented / $cov.javaTotal * 100) } else { 0 }

    Write-Host ""
    Write-Host "╔══════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║           BACKEND RESULTS                   ║" -ForegroundColor Cyan
    Write-Host "╚══════════════════════════════════════════════╝"
    Write-Host ("  ✅ Confirmed   : {0,-5}" -f $confirmed.Count) -ForegroundColor $(if ($notFound.Count -eq 0) { "Green" } else { "White" })
    if ($notFound.Count -gt 0) {
        Write-Host ("  ❌ Not found  : {0,-5}  ← REVIEW THESE IN REPORT" -f $notFound.Count) -ForegroundColor Red
    } else {
        Write-Host ("  ❌ Not found  : 0     ← all backend claims verified!") -ForegroundColor Green
    }
    Write-Host ("  📐 Patterns   : {0,-5} (intentional Xxx placeholders)" -f $patterns.Count) -ForegroundColor DarkGray
    Write-Host ("  Java coverage : {0} / {1} ({2}%)" -f $cov.javaDocumented, $cov.javaTotal, $jPct)
    Write-Host ""
    Write-Host "  Report : $reportFile" -ForegroundColor Cyan
    Write-Host ""
}

Write-Host "Done (backend)." -ForegroundColor Green
Write-Host ""
